<?php

echo "Holaa";
echo "<br>";
echo "Algoritmo para comprar en internet  ";
echo "<br>";
echo "Inicio" ;
echo "<br>";
echo " Paso 1: Seleccionar el sitio donde vas comprar ejemplo ejemplo:mercado libre" ;
echo "<br>";
echo "Paso 2: En el buscador  escribir lo ue deseas comprar";
echo "<br>";
echo "Paso 3: Seleccionar el que te parezca mejor, ya sea por, calidad o precio";
echo "<br>";
echo "Paso 4: meterlo al carrito, entrar en este y seleccionar tu forma de pago  ";
echo "<br>";
echo "paso 5: ingresar tu direccion de entrega ";
echo "<br>";
echo " Paso 6: Confirmar tu compra "; 
echo "<br>";
echo " Paso 7: Esperar su llegada "; 
echo "<br>";
echo " Paso 7: Fin "; 
echo "<br>";
echo "Segundo algoritmo: imprimir los 10 primeros numeros pares  ";
echo "<br>";
echo " Paso 1: Inicio" ;
echo "<br>";
echo "Paso 2: imprimir los primeros 10 numeros son";
echo "<br>";
echo "Paso 3: si el numero es par entonces %2=0";
echo "<br>";
echo "Paso 4: imprimir dicho numero e incrementar el contador mas uno ";
echo "<br>";
echo "paso 5: seguir asi hasta obtener los 10 numeros ";
echo "<br>";
echo " Paso 7: Fin "; 
echo "<br>";
echo "Algoritmo 3";
echo "<br>";
echo "Algoritmo para imprimir el alfabeto ";
echo "<br>";
echo "Inicio" ;
echo "<br>";
echo " Paso 1: Iniciar en letra A" ;
echo "<br>";
echo "Paso 2: mientras a sea menor o igual que z imprimir ";
echo "<br>";
echo "Paso 3: aumentar cada vez uno ";
echo "<br>";
echo "Paso 4: seguir asi hasta llegar a la z ";
echo "<br>";
echo " Paso 7: Fin "; 
echo "<br>";
?>
